### ISSUE TITLE
Option for tftpd to allow overwrite existing files?

### ISSUE THREAD

**Issue by bjoernalbers** [drbig/fx-tftp#2]
Hey Piotr,

I'd find this feature very useful since I only use TFTP put my cisco configs into version control (that means the file actually has to be overwritten each time).
If you don't mind I would send a pull request and add an --force (-f) option.
What do you think?

**Comment by drbig** [comment]
Sure. Though I'd name it `--overwrite (-o)` to make it more explicit. Passed from the bin script and then handled in `RWSimple` with proper logging.
